      PROGRAM TOBOGGAN
      INTEGER TREES, LINES, X, Y, DX, DY, SX
      LOGICAL BITMAP
      DIMENSION BITMAP(31, 400)
C
C LOAD FROM FILE FIRST
      CALL SETUP(BITMAP, LINES)
      TREES = 0
C PERFORM THE SLIDE DOWN
      DX = 3
      DY = 1
      SX = 1
      DO 20 Y = 1, LINES, DY
         DO 10 X = 1, 31
            IF (BITMAP(X, Y).EQ..TRUE..AND.X.EQ.SX)
     1         TREES = TREES + 1
   10    CONTINUE
         SX = SX + DX
         IF (SX.GT.31) SX = SX - 31
   20 CONTINUE
      WRITE(*, 1000) TREES
      STOP
 1000 FORMAT('TOTAL TREES ENCOUNTERED: ', I)
      END
C
C READ THE INPUT FILE AND PARSE IT INTO
C A BITMAP
      SUBROUTINE SETUP(SLOPE, LINES)
      CHARACTER*31 LINE
      INTEGER COL, ROW
      LOGICAL SLOPE
      DIMENSION SLOPE(31, 400)
C
C OPEN FILE AND READ LINE BY LINE
      COL = 1
      OPEN(UNIT=1, FILE='input.dat', ACTION='READ', STATUS='OLD')
   10    READ(UNIT=1, FMT=1000, END=30) LINE
         DO 20 COL = 1, 31
            IF (LINE(COL:COL).EQ.'.') SLOPE(COL, ROW) = .FALSE.
            IF (LINE(COL:COL).EQ.'#') SLOPE(COL, ROW) = .TRUE.
            IF (LINE(COL:COL).NE.'#'.AND.LINE(COL:COL).NE.'.')
     1          WRITE(*,2000) ROW, COL
   20    CONTINUE
         ROW = ROW + 1
         GOTO 10
   30 CONTINUE
      CLOSE(UNIT=1)
      LINES = ROW
      RETURN
 1000 FORMAT(A)
 2000 FORMAT('INVALID CHARACTER AT LINE/COLUMN: ', I, I)
      END
